### ISSUE TITLE
how to  use  alertDialog DialogInterface.OnClickListener ?

### ISSUE THREAD

**Issue by ghost** [YJBeetle/QtAndroidAPI#1]
QAndroidJniObject dialog = QAndroidJniObject(
            "android.app.AlertDialog$Builder",
            "(Landroid/content/Context;)V",
             activity);
    dialog.callObjectMethod(
            "setMessage",
            "(Ljava/lang/CharSequence;)Landroid/app/AlertDialog$Builder;",
            env->NewStringUTF("提示信息")
    );
    dialog.callObjectMethod(
            "setTitle",
            "(Ljava/lang/CharSequence;)Landroid/app/AlertDialog$Builder;",
            env->NewStringUTF("标题")
    );
    dialog.callObjectMethod(
            "setNegativeButton",
            "(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;",
            env->NewStringUTF("取消"),
            NULL
    );
    dialog.callObjectMethod(
            "setPositiveButton",
            "(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;",
            env->NewStringUTF("确定"),
            NULL
    );
    dialog.callObjectMethod(
            "show",
            "()Landroid/app/AlertDialog;"
    );

NULL should use  DialogInterface.OnClickListener . how can I Do ?

**Comment by YJBeetle** [comment]
因为注意到你的代码中使用中文，我就使用我的第一语言中文来回复你的问题了。

你的这个情况可以参考Qt官方文档，写的比较详细：
https://doc.qt.io/qt-5/qtandroidextras-jnimessenger-example.html
https://doc.qt.io/qt-5/qandroidjniobject.html#java-native-methods

你可以写一个java文件
class中 `public static android.content.DialogInterface.OnClickListener clickListener = new...()...` 
然后在cpp中反射之
`auto clickListener = QAndroidJniObject::getStaticObjectField(.../*clickListener*/...)` 

然后就像平时使用这个库一样的使用它即可
```
        auto dialog = AlertDialog_Builder(CONTEXT);
        dialog.setMessage(JSTRING("提示信息"));
        dialog.setTitle(JSTRING("标题"));
        dialog.setNegativeButton(JSTRING("取消"), QAndroidJniObject());
        dialog.setPositiveButton(JSTRING("确定"), clickListener);
        dialog.show();
```

**Comment by YJBeetle** [comment]
我复制了你的代码并且补充了示例：
https://github.com/YJBeetle/QtAndroidAPI/blob/08b3061f7739bdca7886c35e0a3a64f5970ca829/example/QtAndroidApiExample/mainwindow.cpp#L111

在这个示例中，在你点击“确定”之后，将会在日志中打印出"Positive button clicked!"，这句是在cpp中的`fromJavaAlertDialogPositive`函数中打印的

同时注意cmake文件的变动以及java文件
https://github.com/YJBeetle/QtAndroidAPI/blob/08b3061f7739bdca7886c35e0a3a64f5970ca829/example/QtAndroidApiExample/android/src/mainwindow.java
